[window]
opacity = 0.93
padding = { x = 12, y = 12 }
decorations = "None"  # Отключение верхней панели

dynamic_title = true
title = "Alacritty"

[font]
normal = { family = "DejaVu Sans Mono", style = "Regular" }
bold = { family = "DejaVu Sans Mono", style = "Bold" }
italic = { family = "DejaVu Sans Mono", style = "Italic" }
bold_italic = { family = "DejaVu Sans Mono", style = "Bold Italic" }
size = 11.0

[colors.primary]
background = '#0b0b0b' # base
foreground = '#CDD6F4' # text
dim_foreground = '#CDD6F4' # text
bright_foreground = '#CDD6F4' # text

[colors.cursor]
text = '#1E1E2E' # base
cursor = '#F5E0DC' # rosewater

[colors.vi_mode_cursor]
text = '#1E1E2E' # base
cursor = '#B4BEFE' # lavender

[colors.search.matches]
foreground = '#1E1E2E' # base
background = '#A6ADC8' # subtext0

[colors.search.focused_match]
foreground = '#1E1E2E' # base
background = '#00E3A1' # green

[colors.footer_bar]
foreground = '#1E1E2E' # base
background = '#A6ADC8' # subtext0

[colors.hints.start]
foreground = '#1E1E2E' # base
background = '#F9E2AF' # yellow

[colors.hints.end]
foreground = '#1E1E2E' # base
background = '#A6ADC8' # subtext0

[colors.selection]
text = '#1E1E2E' # base
background = '#F5E0DC' # rosewater

[colors.normal]
black = '#45475A' # surface1
red = '#F38BA8' # red
green = '#60FF00' # green
yellow = '#F9E2AF' # yellow
blue = '#39B4FA' # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5' # teal
white = '#BAC2DE' # subtext1

[colors.bright]
black = '#585B70' # surface2
red = '#F38BA8' # red
green = '#A6E3A1' # green
yellow = '#F9E2AF' # yellow
blue = '#89B4FA' # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5' # teal
white = '#A6ADC8' # subtext0

[colors.dim]
black = '#45475A' # surface1
red = '#F38BA8' # red
green = '#A6E3A1' # green
yellow = '#F9E2AF' # yellow
blue = '#89B4FA' # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5' # teal
white = '#BAC2DE' # subtext1


[cursor]
style = "Block"
vi_mode_style = "Underline"

[mouse]
hide_when_typing = true

[terminal]
osc52 = "CopyPaste"

[scrolling]
history = 10000
multiplier = 5

[keyboard]
bindings = [
  { key = "C", mods = "Control", action = "Copy" },             # Копировать Ctrl+C
  { key = "V", mods = "Control", action = "Paste" },            # Вставить Ctrl+V
  { key = "Return", mods = "Alt", action = "SpawnNewInstance" },# Новый терминал Alt+Enter
  { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "Key0", mods = "Control", action = "ResetFontSize" }
]

